### ISSUE TITLE
Deploying to Netlify?

### ISSUE THREAD

**Issue by osseonews** [timlrx/tailwind-nextjs-starter-blog#118]
Curious if anyone can get this to deploy to Netlify. When we tried deploying the current master with no changes at all we get the error below. Any ideas? What is the module 'pnpapi'?

(PS vercel deploys without any problems)

```

12:32:51 AM:   Dependencies installation error                               
12:32:51 AM: ────────────────────────────────────────────────────────────────
12:32:51 AM: ​
12:32:51 AM:   Error message
12:32:51 AM:   A Netlify Function failed to require one of its dependencies.
12:32:51 AM:   Please make sure it is present in the site's top-level "package.json".
​
12:32:51 AM:   In file "/opt/build/repo/netlify/functions/next_blog/next_blog.js"
12:32:51 AM:   Cannot find module 'pnpapi'
12:32:51 AM:   Require stack:
12:32:51 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/node_dependencies/resolve.js
12:32:51 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/node_dependencies/index.js
12:32:51 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/node_modules/@netlify/zip-it-and-ship-it/src/main.js
12:32:51 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/plugins_core/functions/index.js
12:32:51 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/commands/get.js
12:32:51 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/main.js
12:32:51 AM:   - /opt/buildhome/.netlify-build-nvm/versions/node/v12.16.3/lib/node_modules/@netlify/build/src/core/bin.js
```

**Comment by timlrx** [comment]
next.js by default is a full-stack application. If you want to deploy it as a static site on netlify you need to modify the [image component](https://github.com/timlrx/tailwind-nextjs-starter-blog/blob/master/components/Image.js) and use a different provider on a standard HTML img tag and export it as a static site - `next build && next export`

**Comment by osseonews** [comment]
Thanks. Yeah, we have deployed many NextJS apps to Netlify, so we are familiar with the Image issue and how to set everything else up to do deploy properly on NextJs. Actually you can't use next export. Anyway, with this repo there is some other error related to the  module 'pnpapi'. See the error message in the original issue. I've never seen this before. I've seen other people complain of this error on earlier versions of Next, but never on current. So I am curious if anyone has ever seen this error before and how to solve it. None of the solutions have worked thus far.

**Comment by timlrx** [comment]
I have no such issues. Here's a deployed version on netlify - https://focused-hermann-024a00.netlify.app/

**Comment by osseonews** [comment]
Thanks. What's your deploy settings on Netlify? Have you changed next config at all?

**Comment by timlrx** [comment]
No changes were made, beyond changing the image component - I just took the default branch, build, export and deployed it directly. You might want to try deleting your `node_modules` and re-installing the dependencies

**Comment by tebogo37** [comment]
using <img> tag but next export still not working. No "exportPathMap" found in "next.config.js". Generating map from "./pages"

**Comment by timlrx** [comment]
It works for me. Please open a new issue, detailing the modifications you made (if any) and the steps you took, thanks.
